title: DevIsland | Comuunidade de Desenvolvimento 
email: devday@devisland.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devisland.com"

# Build settings
markdown: kramdown

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'node_modules']

include: ['.nojekyll']
